### ISSUE TITLE
Invoke Local Broken

### ISSUE THREAD

**Issue by atwoodjw** [nfour/serverless-build-plugin#20]
```
$ sls invoke local -l -f lunchBot

/Developer/Repositories/serverless-slack/lunchBot/handler.js:1
(function (exports, require, module, __filename, __dirname) { import request from 'request';
                                                              ^^^^^^
SyntaxError: Unexpected token import
...
```

**serverless.yml**
```
service: serverless-slack

provider:
  name: aws
  runtime: nodejs4.3

functions:
  lunchBot:
    handler: lunchBot/handler.default

plugins:
  - serverless-build-plugin
```

**serverless.build.yml**
```
method: bundle

sourceMaps: true
babel: true
uglify: false

modules:
  exclude:
    - aws-sdk

functions:
  lunchBot:
    include:
      - "lunchBot/**"
```
