### ISSUE TITLE
Packager creates an broken ZIP archive

### ISSUE THREAD

**Issue by arabold** [nfour/serverless-build-plugin#21]
When using the build plugin, my Lambda deployments are broken as neither AWS nor my Mac can open the resulting zip files anymore. OSX throws an "Error 21 - is a directory."

I'm suspecting this is due to symbolic links or something in the `node_modules`, specifically in `mysql`, but I haven't had time to confirm this yet or to create a test project. Just wanted to let you know before I'm taking a closer look. It's noteworthy that the official packager of Serverless works without issues.

**Comment by arabold** [comment]
Here's my test environment that reproduces the issue. I've identified the `redis` module as source of the problem:

serverless.yaml
```yaml
service: test-build

provider:
  name: aws
  runtime: nodejs4.3

plugins:
  - serverless-build-plugin

custom:
  build:
    method: bundle
    sourceMaps: false
    babelify: false
    uglify: false
    exclude:
      - "*"
    include:
      - src/**/*
    modules:
      exclude:
        - aws-sdk
      deepExclude:
        - aws-sdk

functions:
  hello:
    handler: src/handler.hello
```

package.json
```json
{ 
  "name": "test-build",
  "version": "1.0.0",
  "dependencies": {
    "redis": "^2.6.3"
  },
  "devDependencies": {
    "serverless-build-plugin": "^0.6.3"
  },
  "author": "",
  "license": "ISC"
}
```

Next step for me is to figure out why it throws up on this.
