### ISSUE TITLE
include pattern not recoginized on Windows

### ISSUE THREAD

**Issue by abhishekbiyala** [nfour/serverless-build-plugin#29]
Hi,

I am trying use include pattern as follows. It works fine when running serverless from Linux and Mac but not on Windows. serverless-build-plugin does not add [SOURCE] on Windows due to this.

```
functions:
  test:
    include:
      - dist/**

```

Thanks,
Abhishek

**Comment by nfour** [comment]
Need more information

- version of serverless-build-plugin
- version of serverless
- any error messages
- layout of produced zip artifact

I've scanned over the obvious location to see if `path` was not normalizing filePaths but cannot see anything standing out.

**Comment by an-sush** [comment]
Hello, 
I encountered the same issue in windows. Here is the version info:
i) serverless-build-plugin@1.1.15
ii) serverless@1.9.0
iii) No error message but it starts packaging [MODULE]. Ideally it should package [SOURCE] followed by [MODULE]
iv) The zip artifact has only node_modules folder and no dist folder

**Comment by nfour** [comment]
@an-sush Can you please show us your `serverless.build.yml`?

**Comment by an-sush** [comment]
I am using serverless.yml with following sections related to build-plugin:
```
custom:
  build:
    method: bundle
    sourceMaps: true
    include:
      - 'dist/**'
plugins:
  - serverless-build-plugin
```

**Comment by jawadst** [comment]
I am seeing the same issue. Here is my `serverless.build.yml`:
```
method: bundle

babel: true
uglify: false

include:
  - src/

functions:
  scrape:
    include:
      - "src/scrape/**"
```

Nothing gets built when I run it on Windows (I get an empty ZIP file) whereas it works fine in a Docker container running Linux.
