### ISSUE TITLE
Function-level module excludes not working

### ISSUE THREAD

**Issue by ckfngod** [nfour/serverless-build-plugin#46]
```
functions:
  my-function:
    modules:
      exclude:
        - winston
```

This is not excluding winston from the my-function package. Am I missing something here?
